# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  test:
    machine:
      enabled: true
    steps:
      - run: echo "Tests can run here!"
  deploy:
    machine:
      enabled: true
    steps:
    - run:
          name: Update apt
          command: ssh $SSH_USER@$SSH_HOST "sudo apt update"

    - run:
          name: Install JDK
          command: ssh $SSH_USER@$SSH_HOST "sudo apt install openjdk-8-jdk -y"
    - run:
          name: Install Maven
          command: ssh $SSH_USER@$SSH_HOST "sudo apt install maven -y"
   # - run:
   #       name: Clone Repo & Install Application Dependencies
   #       command: ssh $SSH_USER@$SSH_HOST "git clone https://github.com/JudithEdh/QA-Fundamental_Project && cd ~/QA-Fundamental_Project"
    - run:
          name: Update Repo 
          command: ssh $SSH_USER@$SSH_HOST "cd ~/QA-Fundamental_Project && git pull origin master"

    - run:
          name: Compile
          command: ssh $SSH_USER@$SSH_HOST "cd ~/QA-Fundamental_Project && mvn clean package"
    - run:
          name: Execute
          command: ssh $SSH_USER@$SSH_HOST "cd ~/QA-Fundamental_Project && mvn exec:java -Dexec.mainClass=com.qa.project_recipies.ProjectRecipiesApplication"
     
workflows:
  version: 2.1
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
